spring:
    application:
        name: customer-service
    server:
        port: 8081
    datasource:
      url: jdbc:postgresql://localhost:5432/customer_db
      username: postgres
      password: huylebron2828
      driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: true



